### ISSUE TITLE
deprecated code in settings.platformsh.php

### ISSUE THREAD

**Issue by omahm** [platformsh-templates/drupal8#11]
I was looking over https://github.com/platformsh-templates/drupal8/blob/master/web/sites/default/settings.platformsh.php#L26
and noticed that drupal_installation_attempted() has been deprecated in favour of 
\Drupal\\Core\\Installer\\InstallerKernel::installationAttempted()

**Comment by Crell** [comment]
This is included in #9, currently blocked on a critical installer bug in Drupal core.
