### ISSUE TITLE
Error after install steps

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh-templates/drupal8#56]
Resulted in the attached error after install steps appeared to complete successfully
![image (3)](https://user-images.githubusercontent.com/5473659/154569667-1982282f-ece5-46f5-947d-8a029bf19aed.png)

**Comment by gilzow** [comment]
So far I'm unable to replicate. A new project, based on this template, in the US-4 region, using the standard installation works as expected. Everything I'm finding online related to the the error message above involves installing a module or theme and not performing a `drush cr` afterwards.
